### ISSUE TITLE
multi-line expressions don't evaluate 

### ISSUE THREAD

**Issue by kennes913** [pwwang/liquidpy#1]
When you have an expression that spans more than a single line, it does not evaluate.

Here's one example:

```python
sample_liquid = """
{% if thing == "a" 
    or thing == "b" 
    or thing == "c" 
    or thing == "d" %}
        {% assign is_thing = "yes" %}
    {{ is_thing }}
{% endif %}
"""
Liquid(sample_liquid).render(thing="a")
```

**Comment by pwwang** [comment]
Statements/Expressions are designed to be on the same line.

This may be supported in the future, but not on my recent plan.

**Comment by kennes913** [comment]
I'll work around. This is worth implementing in my opinion for more complex liquid templates.

**Comment by pwwang** [comment]
That‘ll be nice. You are welcome to submit a PR.

**Comment by pwwang** [comment]
This is supported now in v0.1.0
I will close this for now. Feel free to reopen it if you have any questions.
