### ISSUE TITLE
Ruby vs Python split methods

### ISSUE THREAD

**Issue by kennes913** [pwwang/liquidpy#16]
Observe Ruby's `.split` behavior:
```bash
irb(main):005:0> "/a/b/c/d/".split("/")
=> ["", "a", "b", "c", "d"]
```
Compared to Python's:
```bash
In [1]: "/a/b/c/d/".split("/")
Out[1]: ['', 'a', 'b', 'c', 'd', '']
```

I think by default you should mimic what Ruby does or at least provided an optional flag for Python splitting vs Ruby splitting.  This matters for string iteration, concatenation and or any complicated string operation on which some logic depends and you're trying to produce the same behavior as Shopify Liquid templates or any derivatives from that such as [Looker](https://docs.looker.com/reference/liquid-variables).

I can **help** handle this if you like. Providing a flag may be too invasive.

**Comment by pwwang** [comment]
What about a liquid filter like:
```liquid
{{ ", Paul, George, Ringo, " | @ruby_split: ", " }}
{# gives ['', 'Paul', 'George', 'Ringo'] #}
{# instead of ['', 'Paul', 'George', 'Ringo', ''] #}
```
?

**Comment by kennes913** [comment]
That is what I'm doing in my code and "registering" it as part of the environment ☝️

**Comment by kennes913** [comment]
Also, related, this snippet on your docs
```python 
def someComplicatedLogic(val):
	# your logic goes here
	return val

liq = Liquid('{{ "value" | myfilter }}', {'myfilter': someComplicatedLogic})
liq.render()
```
I think should be:
```python
liq = Liquid('{{ "value" | myfilter }}', **{'myfilter': someComplicatedLogic})
```

**Comment by pwwang** [comment]
Oh, nice catch!

**Comment by pwwang** [comment]
If implementing something like `ruby_split` is easy for you. I would close this for now. 
Thanks for contributing!
