### ISSUE TITLE
Does it support "random" function?  How to use?

### ISSUE THREAD

**Issue by lxsyz** [pwwang/liquidpy#17]
I read the documents and don't find the description about "random". Does it support?
I used ' {% import random %}' which will throw exception

**Comment by pwwang** [comment]
I am able to import it.
Can you provide the traceback and the exception, as well as the version of `liquidpy` you used?

```python console
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import liquid
>>> liq = liquid.Liquid("{% import random %}{{random | .random:}}")
>>> liq.render()
'0.5458922171193153'
>>>
```

**Comment by lxsyz** [comment]
My version of liquidpy is too old. And when I change the version, it's ok. Thank you very much.
