### ISSUE TITLE
support for Liquid forloop object

### ISSUE THREAD

**Issue by jfelectron** [pwwang/liquidpy#2]
-- Iterate over the day windows we want
          {% for day in days_splits %}
            -- Handling of first window
            {% if forloop.first %}

NameError: name 'forloop' is not defined

https://help.shopify.com/en/themes/liquid/objects/for-loops

**Comment by pwwang** [comment]
This is supported now in v0.1.0
I will close this for now. Feel free to reopen it if you have any questions.
