### ISSUE TITLE
How to integrate liquidpy to django framework

### ISSUE THREAD

**Issue by futuri** [pwwang/liquidpy#27]
How liquidpy should be properly integrated into django

I was testing liquidpy and it works great except when using `{% include" test.liquid "%}` it gives me the error: `Exception Value:
No such tag: include`

The way I integrate it is as follows:
![Captura de pantalla de 2020-07-25 00-25-12](https://user-images.githubusercontent.com/2472615/88449547-673a6b80-ce0d-11ea-94cf-26e450b577fb.png)

![Captura de pantalla de 2020-07-25 00-25-38](https://user-images.githubusercontent.com/2472615/88449550-6b668900-ce0d-11ea-814a-36de23b9228a.png)

without configuring settings.py

_Thanks for creating liquidpy_

**Comment by pwwang** [comment]
Which version of `liquidpy` are you using?

You can check it via:
```
python -c 'import liquid; print(liquid.__version__);'
```

**Comment by futuri** [comment]
I used the `lark` branch, the command to see the version did not work,

![Captura de pantalla de 2020-07-25 19-56-14](https://user-images.githubusercontent.com/2472615/88469134-7a077b80-ceb3-11ea-9951-bbf4a75a0449.png)

I now installed the other version of the `master` branch, now it works include the file test.liquid, and also to see the version of liquidpy

![Captura de pantalla de 2020-07-25 20-28-37](https://user-images.githubusercontent.com/2472615/88469285-95738600-ceb5-11ea-985c-8f05d81aeb72.png)

I still have doubts about how to correctly integrate to django

**Comment by pwwang** [comment]
`lark` and `larkone` branchs are just experiments to re-implement it and make it compatible with shopify's liquid. Tags like `render`, `include`, `extends` are not implemented yet (You can find the list of tags that are implemented [here](https://github.com/pwwang/liquidpy/tree/lark/liquid/common/tags) form `lark` branch). The lexer is pretty slow using `lark` for both branches. We are still figuring out a way to speed it up or write our own lexer. We won't go further until we resolve the speed issue. I would hold for this but you are very welcome if you want to contribute to the issue as well.

**Comment by pwwang** [comment]
The package is now remodeled in a safer way and compatible with the standard liquid template engine. `include` tag is not supported in the standard liquid, but just in the `Jekyll` variation. However, we did add some additional tags to the standard liquid, including `include` tag. Please read the docs for more information.

**Comment by pwwang** [comment]
Feel free to re-open this if you have further related questions.
