### ISSUE TITLE
TagBlock not in list when rendering same template more than once

### ISSUE THREAD

**Issue by bowmanjd** [pwwang/liquidpy#29]
Recently, I am unable to render a template more than once if it has `extends` in it.

See [this gist](https://gist.github.com/bowmanjd/72d7b3e2cdf506025db34a2df3ead3e4) for example code. The first render succeeds, and the second fails.

The resulting error on the second try: `ValueError: <TagBlock('test::body', compact 'none', line 2, column 14)> is not in list`

How can I help?

**Comment by pwwang** [comment]
Thanks for reporting!

This should be fixed at `0.6.1`. Try `pip install -U liquidpy` to check it out.

Feel free to reopen with related issues.

**Comment by bowmanjd** [comment]
Works for me! Thank you so much.
