### ISSUE TITLE
Best way to add another file of custom filters?

### ISSUE THREAD

**Issue by sam-hoffman** [pwwang/liquidpy#44]
I'd like to use liquidpy in wild mode and add another external file of filters (in addition to `filters/wild.py`) instead of having to define them within templates. Is it possible to add more filters? If so, what's the best syntax to do that?

**Comment by pwwang** [comment]
You can pass your own filters to the `Liquid` constructor:

```python
>>> from liquid import Liquid
>>> def myfilter(a):
...     return a + 10
... 
>>> Liquid("{{a | add10}}", mode="wild", from_file=False, filters={"add10": myfilter}).render(a=1)
'11'
```

This way, you can definitely define your own filters in a separate file, and then do `from myfilters import myfilter`.

If you want a manager for a better housekeeping of your filters (in, say, `myfilters.py`), you can also do:
```python
from liquid.filters.manager import FilterManager

mgr = FilterManager()

@mgr.register("add10")
def myfilter(a):
    return a + 10
```

Then when constructing a liquid object:
```python
from myfilters import mgr

Liquid("{{a | add10}}", mode="wild", from_file=False, filters=mgr.filters).render(a=1)
```

If you want to use `jinja2`'s environment, you could also try `pass_environment`. See `filters/wild.py`.

**Comment by sam-hoffman** [comment]
awesome, thanks!

**Comment by pwwang** [comment]
Not at all. Closing it for now. Feel free to open another if you have any other questions.
