### ISSUE TITLE
Issue with JSON/list parsing in certain cases

### ISSUE THREAD

**Issue by frikky** [pwwang/liquidpy#50]
Hey again!

We've had some trouble recently with complex data, and I've been trying to figure out a very simple example that breaks if done wrong. Here goes:
1. Open up the playground https://pwwang.github.io/liquidpy/playground/
2. Set version to "Wild"
3. Paste in the following. This works entirely as expected!
```
{{ [{"id": "1"}] | size }}

{{ a | upper }}
```

4. Now, let's do a little switcheroo. This seems to break somehow, and I'm not sure where or how to look for a fix.
```
{{ a | upper }}

{{ [{"id": "1"}] | size }}
```

This seems to only be the case when trying to handle JSON within a list, and doing it AFTER another filter has been used previously. The main place we see issues with it is if you e.g. try to use the "size" filter multiple times, and it contains JSON.

Cheers - please tell me how we can help :)

**Comment by pwwang** [comment]
Fixed by [0.7.6](https://github.com/pwwang/liquidpy/pull/51).

This is tricky, but a nice catch!

**Comment by frikky** [comment]
That was fast!! Glad we're using this project. 

Where is the sponsor button? :eyes:

**Comment by pwwang** [comment]
Hey, thanks for asking! Really appreciate it. But let's see if it can benefit more people in the future.
