### ISSUE TITLE
 Removal of newline at end of template

### ISSUE THREAD

**Issue by sanderland** [pwwang/liquidpy#58]
When ending a template with newlines, exactly one is silently removed, and it is not clear why or how to prevent this.

```
from liquid import Liquid
Liquid("hello {{x}}!\n\n", from_file=False).render(x="Sander")
# =>  'hello Sander!\n'
```

**Comment by pwwang** [comment]
See https://github.com/pallets/jinja/issues/848

You can pass additional arguments to jinja env with Liquid:

```python
from liquid import Liquid
x = Liquid("hello {{x}}!\n\n", from_file=False, keep_trailing_newline=True).render(x="Sander")
# =>  'hello Sander!\n\n'
```

**Comment by pwwang** [comment]
Feel free to reopen if more related questions arise.
