### ISSUE TITLE
How to include a file without specifying it's file extension suffix [.liquid]?

### ISSUE THREAD

**Issue by martibook** [pwwang/liquidpy#59]
Hi,

I have two .liquid files, inside first.liquid:
{% include "second.liquid" %} works
{% include "second" %} will throw TemplateNotFound

Is there anyway to support {% include "second" %}?

Thanks!

**Comment by pwwang** [comment]
The file doesn't have to have the `liquid` extension. See https://github.com/pwwang/liquidpy/blob/master/tests/wild/test_include.py

**Comment by martibook** [comment]
Does it make sense to ignore every kind of file extension as long as the file name is correct? 

e.g
`{% include "have_a_nice_day" %}` 
works for
"have_a_nice_day.txt"
"have_a_nice_day.liquid"
"have_a_nice_day.html"

**Comment by pwwang** [comment]
> Does it make sense to ignore every kind of file extension as long as the file name is correct?
> 
> e.g `{% include "have_a_nice_day" %}` works for "have_a_nice_day.txt" "have_a_nice_day.liquid" "have_a_nice_day.html"

I am confused. Do you mean `have_a_nice_day` should actually include `have_a_nice_day.txt`?

**Comment by martibook** [comment]
I understand that seems not helpful to everyone, though it exactly meet my needs currently.
Let's close this one, thanks!

**Comment by pwwang** [comment]
You can also define a tag if you want, to make it work this way. You can refer to 

https://github.com/pwwang/liquidpy/blob/master/liquid/tags/jekyll.py

to see how it's implemented.

**Comment by pwwang** [comment]
You don't have to modify the code. I am just showing you an example to add a tag.

```python
from liquid.tags.standard import standard_tags

@standard_tags.register
def my_include(token, parser):
    ...
```

**Comment by martibook** [comment]
Wow that was inspiring.

I've written something like to append ".liquid" at the end if there was not, but it does not work, should I explicitly adding some override decorator? Or did I miss anything?
```
        @standard_tags.register
        def include(token: Token, parser: Parser) -> nodes.Node:
            """The {% include ... %} tag"""
            node = nodes.Include(lineno=token.lineno)
            path = parser.parse_expression()
            if parser.stream.filename:
                node.template = nodes.Add(
                    nodes.Add(
                        nodes.Const(path.dirname(parser.stream.filename)),
                        nodes.Const(path.sep),
                    ),
                    path,
                )
            else:
                node.template = path

            # Append `.liquid` if not already present
            node.template = nodes.CondExpr(
                nodes.Test(
                    path,
                    'endswith',  # Check if the string ends with `.liquid`
                    [nodes.Const('.liquid')],
                ),
                path,  # Use original path if it ends with `.liquid`
                nodes.Add(path, nodes.Const('.liquid')),  # Append `.liquid` if not
            )    

            node.ignore_missing = False
            return parser.parse_import_context(node, True)
```

Appreciation in advance.

**Comment by pwwang** [comment]
```python
from jinja2 import nodes
from liquid import Liquid
from liquid.tags.standard import standard_tags


@standard_tags.register
def include_no_ext(token, parser):
    node = nodes.Include(lineno=token.lineno)
    path = parser.parse_expression()
    path.value = path.value + ".ini"
    node.template = path
    node.ignore_missing = False
    return parser.parse_import_context(node, True)


liquid = Liquid("{% include_no_ext 'tox' %}", from_file=False)
print(liquid.render())
```

Prints content of `tox.ini`:

```
[flake8]
ignore = E203, W503, E731
per-file-ignores =
    # imported but unused
    __init__.py: F401
max-line-length = 89
```

**Comment by pwwang** [comment]
Unfortunately, `include` is a `jinja2`-builtin tag. There is no way for `liquidpy` to manage it. The extension only applied to the non-existing tags.

You either write a `jinja2` extension yourself or use a different name other than `include`.

**Comment by martibook** [comment]
You're right, I need to override something from jinja2.

I've figured it out.
With
```
class CustomLoader(FileSystemLoader):
    def get_source(self, environment, template):
        if not template.endswith('.liquid'):
            template += '.liquid'
        return super().get_source(environment, template)
```

I could interrupt the normal include flow.

**Comment by martibook** [comment]
But I've still got a problem.

Currently I have something like
```
        env = Environment(
            loader=CustomLoader(self.search_paths),  # Update with your template directory
        )
        self.template = env.get_template(template_path)
```
to solve "include" issue.


But this way I can't leverage tag extensions from liquidpy, in the end, I got lots of exceptions like tags(e.g. Unless) not supported.


Is there anyway I could have tag implementations from liquidpy even I use
`self.template = env.get_template(template_path)` instead of Liquid constructor to load template?

**Comment by pwwang** [comment]
You can pass a jinja2 environment to `Liquid()`

**Comment by martibook** [comment]
Ahh, inside Liquid constructor, it happens to have `ChoiceLoader` cover my custom loader, which also has a get_source method override mine. 😭 
```
        loader = env_args.pop("loader", None)
        fsloader = FileSystemLoader(search_paths)  # type: ignore
        if loader:
            loader = ChoiceLoader([loader, fsloader])
        else:
            loader = fsloader
```

**Comment by pwwang** [comment]
Can you try to pass the loader directly to `Liquid()`?

`Liquid(..., loader=CustomLoader())`

**Comment by martibook** [comment]
Wow... it works.

Oh I see after carefully reading the Liquid constructor, there're many details.

Thank you!! my issues solved thoroughly.

🌻 🌻
