### ISSUE TITLE
Is it possible to support file_exists extension?

### ISSUE THREAD

**Issue by martibook** [pwwang/liquidpy#60]
I have the following content in my xx.liquid file:

...
{% assign exist = action_path | file_exists %}
{%- if exist -%}
{%- include action_path -%}
{%- endif -%}
...

But file_exists  is not yet supported in this library, do we have alternatives to support file existence check before including them?

Thanks!

Could you provide some guidance to make contribution to this library, I'm more than willing to help if I'm able to.

**Comment by pwwang** [comment]
Have you noticed that you can pass `filters` to the `Liquid` constructor?

https://pwwang.github.io/liquidpy/api/liquid.liquid/

**Comment by martibook** [comment]
Is there an existing filter named `file_exists` that I can pass into the constructor?
Or any filters doing the same job: check existence of a file_path.

**Comment by martibook** [comment]
If I should implement `file_exists` myself before putting it into the Liquid constructor, where is the right place to implement it?

**Comment by pwwang** [comment]
```python
from os import path

Liquid(..., filters = {"file_exists": path.exists})
```

**Comment by martibook** [comment]
A problem with the solution is that there's no memory of `search_paths` which results in false-negative of the file check.

**Comment by pwwang** [comment]
Then you can write a function with `search_paths` considered:

```python
from os import path
search_paths = [...]


def file_exists(x):
    return any(path.exists(path.join(spath, x)) for spath in search_paths)


Liquid(..., search_paths = search_paths, filters = {"file_exists": file_exists})
```

**Comment by martibook** [comment]
It works.
